# Site
name: 'Sirherobrine23'
description: 'Site em que quase tudo acontece. '
logo: ' /assets/images/logo.jpg'
favicon: ' /assets/images/favicon.ico'
baseurl: ''
disqus: 'Site Alpha'
email: 'srherobrine20@gmail.com'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&id=8c3d2d214b'
 
include: ["_pages"]
permalink: /:title/
 
# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sirherobrine23:
      name:           sirherobrine23
      site:           https://www.sirherobrine23.org
      avatar:         /assets/images/sh23.jpg
      bio:            "Oi como estou sempre tendo algo na cabe√ßa sempre acabo colocando no github ou em meu site"
      email:          srherobrine20@gmail.com
      twitter:        https://twitter.com/sirherobrine23
 
# Defaults
defaults:
 
  # all posts
  - scope:
      path: "_posts"
    #values:
     # layout: post
     # author: sirherobrine23
     # avatar: /assets/images/sh23.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge
 
# Paginate
paginate: 15
 
 
 
# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
 
